site_name: Opioid Trends in Indiana
site_url: https://node.cns.iu.edu/client/opioid-trends/
site_description: Opioid Trends in Indiana using the IADC Dataset
site_author: Cyberinfrastructure for Network Science Center & Regenstrief Institute

repo_url: https://github.com/cns-iu/opioid-trends/

# Set edit_uri to "" to remove the "Edit on GitHub" link
# edit_uri: ""

use_directory_urls: false

nav:
  - About: index.md
  - Change Log: CHANGELOG.md
  - Dataset:
    - Sources: sources/index.md
    - Generated Data: data/index.md
  - Visualizations:
    - Opioid Trends Over Time: chart/index.md
    - Opioid Trends on the Indiana Map: geomap/index.md
    - Demographics: demographics/index.md
    - Diagnosis: diagnosis/index.md
    - Fills: fills/index.md
    - Encounters: encounters/index.md
    - Labs: labs/index.md
  - Help: help/index.md

plugins:
  - search
  - macros:
      module_name: mkdocs_macros

extra:
  source_prefix: 'https://github.com/cns-iu/opioid-trends/blob/develop/'

  # MkPDFs doesn't work with readthedocs theme and
  # the generated schema html. So for now, we'll
  # turn PDF generation off.
  # TODO: Report bugs to mkpdfs-mkdocs repo.
  # - mkpdfs:
  #     output_path: pdf/a2agc-documentation.pdf

theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True
