site_name: IADC Visualizations
site_url: https://node.cns.iu.edu/client/opioid-trends
site_description: Indiana Addictions Data Commons (IADC) Visualizations
site_author: CNS & Regenstrief Institute

repo_url: https://github.com/cns-iu/opioid-trends/

# Set edit_uri to "" to remove the "Edit on GitHub" link
# edit_uri: ""

use_directory_urls: false

nav:
  - About: index.md
  - '&#x1F517; Schema Browser': schema/index.html

plugins:
  - search
  - macros

# Module defining additional variables/macros for jinja2 processing
python_module: mkdocs_macros_extras

extra:
  source_prefix: 'https://github.com/cns-iu/opioid-trends/blob/develop/'

  # MkPDFs doesn't work with readthedocs theme and
  # the generated schema html. So for now, we'll
  # turn PDF generation off.
  # TODO: Report bugs to mkpdfs-mkdocs repo.
  # - mkpdfs:
  #     output_path: pdf/a2agc-documentation.pdf

theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True
