BEGIN;

-- DEMOGRAPHICS
DROP INDEX IF EXISTS DEMOGRAPHICS_STUDY_ID_INDEX;

CREATE INDEX DEMOGRAPHICS_STUDY_ID_INDEX ON DEMOGRAPHICS (STUDY_ID);

-- DIAGNOSES
DROP INDEX IF EXISTS DIAGONSES_STUDY_ID_INDEX;
DROP INDEX IF EXISTS DIAGONSES_DX_DATE_INDEX;
DROP INDEX IF EXISTS DIAGONSES_DX_CODE_TYPE_INDEX;

CREATE INDEX DIAGONSES_STUDY_ID_INDEX ON DIAGNOSES (STUDY_ID);
CREATE INDEX DIAGONSES_DX_DATE_INDEX ON DIAGNOSES (DX_DATE);
CREATE INDEX DIAGONSES_DX_CODE_TYPE_INDEX ON DIAGNOSES (DX_CODE_TYPE);

-- EMS
DROP INDEX IF EXISTS EMS_INC_INCIDENTID_INDEX;
DROP INDEX IF EXISTS EMS_INC_INCIDENTDATE_INDEX;
DROP INDEX IF EXISTS EMS_NARCANRUN_INDEX;

CREATE INDEX EMS_INC_INCIDENTID_INDEX ON EMS (INC_INCIDENTID);
CREATE INDEX EMS_INC_INCIDENTDATE_INDEX ON EMS (INC_INCIDENTDATE);
CREATE INDEX EMS_NARCANRUN_INDEX ON EMS (NARCANRUN);

-- ENCOUNTERS
DROP INDEX IF EXISTS ENCOUNTERS_STUDY_ID_INDEX;
DROP INDEX IF EXISTS ENCOUNTERS_ENCOUNTER_ID_INDEX;

CREATE INDEX ENCOUNTERS_STUDY_ID_INDEX ON ENCOUNTERS (STUDY_ID);
CREATE INDEX ENCOUNTERS_ENCOUNTER_ID_INDEX ON ENCOUNTERS (ENCOUNTER_ID);

-- FILLS
DROP INDEX IF EXISTS FILLS_STUDY_ID_INDEX;
DROP INDEX IF EXISTS FILLS_FILL_DATE_INDEX;

CREATE INDEX FILLS_STUDY_ID_INDEX ON FILLS (STUDY_ID);
CREATE INDEX FILLS_FILL_DATE_INDEX ON FILLS (FILL_DATE);

-- LABS
DROP INDEX IF EXISTS LABS_STUDY_ID_INDEX;
DROP INDEX IF EXISTS LABS_TEST_DATE_INDEX;
DROP INDEX IF EXISTS LABS_LAB_CODE_TYPE_INDEX;

CREATE INDEX LABS_STUDY_ID_INDEX ON LABS (STUDY_ID);
CREATE INDEX LABS_TEST_DATE_INDEX ON LABS (TEST_DATE);
CREATE INDEX LABS_LAB_CODE_TYPE_INDEX ON LABS (LAB_CODE_TYPE);

END;
