-- Load Source Database --

ATTACH DATABASE 'raw-data/original/box-health/R2767_Data.db' AS src;
-- ATTACH DATABASE ':memory:' AS src;
-- .restore 'src' 'raw-data/original/box-health/R2767_Data.db';

DROP TABLE IF EXISTS "DIAGNOSES_AND_DEMO";
CREATE TABLE "DIAGNOSES_AND_DEMO" AS
  SELECT
    -- date(DX_DATE, 'start of month') AS "PERIOD", -- Monthly Period
    strftime('%Y', DX_DATE) || CASE 
      WHEN cast(strftime('%m', DX_DATE) as integer) BETWEEN 1 AND 3 THEN '-01-01'
      WHEN cast(strftime('%m', DX_DATE) as integer) BETWEEN 4 and 6 THEN '-04-01'
      WHEN cast(strftime('%m', DX_DATE) as integer) BETWEEN 7 and 9 THEN '-07-01'
      ELSE '-10-01'
    END AS "PERIOD", -- Quarterly Period
    STUDY_ID,
    THREE_FILL_FLAG,
    DX_CODE_TYPE
  FROM src.DIAGNOSES
    JOIN src.DEMOGRAPHICS USING(STUDY_ID)
  ORDER BY period;

DROP TABLE IF EXISTS "FILLS_AND_DEMO";
CREATE TABLE "FILLS_AND_DEMO" AS
  SELECT
    -- date(DX_DATE, 'start of month') AS "PERIOD", -- Monthly Period
    strftime('%Y', FILL_DATE) || CASE 
      WHEN cast(strftime('%m', FILL_DATE) as integer) BETWEEN 1 AND 3 THEN '-01-01'
      WHEN cast(strftime('%m', FILL_DATE) as integer) BETWEEN 4 and 6 THEN '-04-01'
      WHEN cast(strftime('%m', FILL_DATE) as integer) BETWEEN 7 and 9 THEN '-07-01'
      ELSE '-10-01'
    END AS "PERIOD", -- Quarterly Period
    STUDY_ID,
    THREE_FILL_FLAG
  FROM src.FILLS
    JOIN src.DEMOGRAPHICS USING(STUDY_ID)
  WHERE DRUG_TYPE == 'OPIOID'
  ORDER BY period;


-- Prescriptions data
DROP TABLE IF EXISTS "FILLS_AGG";
CREATE TABLE "FILLS_AGG" AS
  SELECT
    PERIOD,
    count(*) AS "N_OPIOID_PRESCRIPTIONS", -- O1 # opioid prescriptions
    count(DISTINCT STUDY_ID) AS "N_OPIOID_PRESCRIBERS" -- O2 # individuals with opioid prescriptions
  FROM FILLS_AND_DEMO
  GROUP BY period;

DROP TABLE IF EXISTS "FILLS_AGG_CHRONIC";
CREATE TABLE "FILLS_AGG_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OPIOID_PRESCRIBERS_CHRONIC"
  FROM FILLS_AND_DEMO
  WHERE THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "FILLS_AGG_NONCHRONIC";
CREATE TABLE "FILLS_AGG_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OPIOID_PRESCRIBERS_NONCHRONIC"
  FROM FILLS_AND_DEMO 
  WHERE THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Opioid Use
DROP TABLE IF EXISTS "DIAGNOSES_AGG_OPIOID";
CREATE TABLE "DIAGNOSES_AGG_OPIOID" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OPIOID_DIAGNOSED" -- O4 # individuals diagnosed with opioid misuse
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OPIOID_USE_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_OPIOID_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_OPIOID_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OPIOID_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OPIOID_USE_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_OPIOID_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_OPIOID_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OPIOID_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OPIOID_USE_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Opioid Poisoning
DROP TABLE IF EXISTS "DIAGNOSES_AGG_OPIOID_POISONING";
CREATE TABLE "DIAGNOSES_AGG_OPIOID_POISONING" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OPIOID_POISONING_DIAGNOSED"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OPIOID_POISONING_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_OPIOID_POISONING_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_OPIOID_POISONING_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OPIOID_POISONING_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OPIOID_POISONING_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_OPIOID_POISONING_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_OPIOID_POISONING_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OPIOID_POISONING_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OPIOID_POISONING_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- STD
DROP TABLE IF EXISTS "DIAGNOSES_AGG_STD";
CREATE TABLE "DIAGNOSES_AGG_STD" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_STD_DIAGNOSED" -- C1 # individuals diagnosed with sexually transmitted diseases
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'STD_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_STD_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_STD_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_STD_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'STD_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_STD_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_STD_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_STD_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'STD_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- HIV
DROP TABLE IF EXISTS "DIAGNOSES_AGG_HIV";
CREATE TABLE "DIAGNOSES_AGG_HIV" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_HIV_DIAGNOSED" -- C3 # individuals diagnosed with HIV/AIDS
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'HIV_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_HIV_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_HIV_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_HIV_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'HIV_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_HIV_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_HIV_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_HIV_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'HIV_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Mental health disorder
DROP TABLE IF EXISTS "DIAGNOSES_AGG_MENTAL";
CREATE TABLE "DIAGNOSES_AGG_MENTAL" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_MENTAL_DIAGNOSED" -- C4 # individuals diagnosed with mental health disorders
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'ENCOUNTER_MENTAL_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_MENTAL_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_MENTAL_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_MENTAL_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'ENCOUNTER_MENTAL_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_MENTAL_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_MENTAL_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_MENTAL_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'ENCOUNTER_MENTAL_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Substance abuse disorder
DROP TABLE IF EXISTS "DIAGNOSES_AGG_SUD";
CREATE TABLE "DIAGNOSES_AGG_SUD" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_SUD_DIAGNOSED" -- C5 # individuals diagnosed with substance abuse diagnoses
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'SUBSTANCE_USE_DISORDER'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_SUD_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_SUD_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_SUD_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'SUBSTANCE_USE_DISORDER' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_SUD_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_SUD_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_SUD_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'SUBSTANCE_USE_DISORDER' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Alcohol poisoning
DROP TABLE IF EXISTS "DIAGNOSES_AGG_ALCOHOL";
CREATE TABLE "DIAGNOSES_AGG_ALCOHOL" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_ALCOHOL_DIAGNOSED"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'ALCOHOL_POISONING_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_ALCOHOL_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_ALCOHOL_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_ALCOHOL_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'ALCOHOL_POISONING_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_ALCOHOL_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_ALCOHOL_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_ALCOHOL_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'ALCOHOL_POISONING_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Benzo poisoning
DROP TABLE IF EXISTS "DIAGNOSES_AGG_BENZO";
CREATE TABLE "DIAGNOSES_AGG_BENZO" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_BENZO_DIAGNOSED"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'BENZO_POISONING_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_BENZO_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_BENZO_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_BENZO_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'BENZO_POISONING_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_BENZO_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_BENZO_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_BENZO_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'BENZO_POISONING_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Drug poisoning
DROP TABLE IF EXISTS "DIAGNOSES_AGG_DRUG";
CREATE TABLE "DIAGNOSES_AGG_DRUG" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_DRUG_DIAGNOSED"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'ILLICIT_DRUG_POISONING_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_DRUG_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_DRUG_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_DRUG_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'ILLICIT_DRUG_POISONING_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_DRUG_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_DRUG_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_DRUG_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'ILLICIT_DRUG_POISONING_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Other poisoning
DROP TABLE IF EXISTS "DIAGNOSES_AGG_OTHER";
CREATE TABLE "DIAGNOSES_AGG_OTHER" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OTHER_DIAGNOSED"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OTHER_POISONING_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_OTHER_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_OTHER_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OTHER_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OTHER_POISONING_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_OTHER_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_OTHER_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OTHER_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OTHER_POISONING_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Overdose
DROP TABLE IF EXISTS "DIAGNOSES_AGG_OVERDOSE";
CREATE TABLE "DIAGNOSES_AGG_OVERDOSE" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OVERDOSE_DIAGNOSED"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OVERDOSE'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_OVERDOSE_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_OVERDOSE_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OVERDOSE_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OVERDOSE' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_OVERDOSE_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_OVERDOSE_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_OVERDOSE_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'OVERDOSE' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;


-- Stimulant poisoning
DROP TABLE IF EXISTS "DIAGNOSES_AGG_STIMULANT";
CREATE TABLE "DIAGNOSES_AGG_STIMULANT" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_STIMULANT_DIAGNOSED"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'STIMULANT_POISONING_DX'
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_STIMULANT_CHRONIC";
CREATE TABLE "DIAGNOSES_AGG_STIMULANT_CHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_STIMULANT_DIAGNOSED_CHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'STIMULANT_POISONING_DX' AND THREE_FILL_FLAG == 1
  GROUP BY period;

DROP TABLE IF EXISTS "DIAGNOSES_AGG_STIMULANT_NONCHRONIC";
CREATE TABLE "DIAGNOSES_AGG_STIMULANT_NONCHRONIC" AS
  SELECT
    PERIOD,
    count(DISTINCT STUDY_ID) AS "N_STIMULANT_DIAGNOSED_NONCHRONIC"
  FROM DIAGNOSES_AND_DEMO
  WHERE DX_CODE_TYPE == 'STIMULANT_POISONING_DX' AND THREE_FILL_FLAG IS NULL
  GROUP BY period;

-- Aggregate view
DROP TABLE IF EXISTS "ALL_AGGREGATES";
CREATE TABLE "ALL_AGGREGATES" AS
  SELECT *
  FROM
    FILLS_AGG AS F
    LEFT JOIN FILLS_AGG_CHRONIC USING(period)
    LEFT JOIN FILLS_AGG_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_OPIOID USING(period)
    LEFT JOIN DIAGNOSES_AGG_OPIOID_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_OPIOID_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_OPIOID_POISONING USING(period)
    LEFT JOIN DIAGNOSES_AGG_OPIOID_POISONING_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_OPIOID_POISONING_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_STD USING(period)
    LEFT JOIN DIAGNOSES_AGG_STD_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_STD_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_HIV USING(period)
    LEFT JOIN DIAGNOSES_AGG_HIV_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_HIV_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_MENTAL USING(period)
    LEFT JOIN DIAGNOSES_AGG_MENTAL_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_MENTAL_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_SUD USING(period)
    LEFT JOIN DIAGNOSES_AGG_SUD_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_SUD_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_ALCOHOL USING(period)
    LEFT JOIN DIAGNOSES_AGG_ALCOHOL_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_ALCOHOL_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_BENZO USING(period)
    LEFT JOIN DIAGNOSES_AGG_BENZO_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_BENZO_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_DRUG USING(period)
    LEFT JOIN DIAGNOSES_AGG_DRUG_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_DRUG_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_OTHER USING(period)
    LEFT JOIN DIAGNOSES_AGG_OTHER_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_OTHER_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_OVERDOSE USING(period)
    LEFT JOIN DIAGNOSES_AGG_OVERDOSE_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_OVERDOSE_NONCHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_STIMULANT USING(period)
    LEFT JOIN DIAGNOSES_AGG_STIMULANT_CHRONIC USING(period)
    LEFT JOIN DIAGNOSES_AGG_STIMULANT_NONCHRONIC USING(period)
  WHERE cast(strftime('%Y', F.period) as integer) <= 2018 AND cast(strftime('%Y', F.period) as integer) >= 2009;

DROP TABLE IF EXISTS "ALL_AGGREGATES_ROW_BASED";
CREATE TABLE "ALL_AGGREGATES_ROW_BASED" AS
  SELECT * FROM (
-- Opioid Use
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Opioid Use' AS "DATA_VARIABLE",
      100 * cast(N_OPIOID_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_OPIOID_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Opioid Use' AS "DATA_VARIABLE",
      100 * cast(N_OPIOID_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_OPIOID_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Opioid Use' AS "DATA_VARIABLE",
      100 * cast(N_OPIOID_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
      N_OPIOID_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- Opioid Poisoning
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Opioid Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_OPIOID_POISONING_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_OPIOID_POISONING_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Opioid Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_OPIOID_POISONING_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_OPIOID_POISONING_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Opioid Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_OPIOID_POISONING_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
      N_OPIOID_POISONING_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- STD
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'STD' AS "DATA_VARIABLE",
      100 * cast(N_STD_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_STD_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'STD' AS "DATA_VARIABLE",
      100 * cast(N_STD_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_STD_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'STD' AS "DATA_VARIABLE",
      100 * cast(N_STD_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
      N_STD_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- HIV
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'HIV' AS "DATA_VARIABLE",
      100 * cast(N_HIV_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_HIV_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'HIV' AS "DATA_VARIABLE",
      100 * cast(N_HIV_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_HIV_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'HIV' AS "DATA_VARIABLE",
      100 * cast(N_HIV_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
      N_HIV_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- Mental health disorder
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Mental Health' AS "DATA_VARIABLE",
      100 * cast(N_MENTAL_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_MENTAL_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Mental Health' AS "DATA_VARIABLE",
      100 * cast(N_MENTAL_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_MENTAL_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Mental Health' AS "DATA_VARIABLE",
       100 * cast(N_MENTAL_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
       N_MENTAL_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- Substance abuse disorder
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Substance Abuse Disorder' AS "DATA_VARIABLE",
      100 * cast(N_SUD_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_SUD_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Substance Abuse Disorder' AS "DATA_VARIABLE",
      100 * cast(N_SUD_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_SUD_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Substance Abuse Disorder' AS "DATA_VARIABLE",
       100 * cast(N_SUD_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
       N_SUD_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- Alcohol poisoning
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Alcohol Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_ALCOHOL_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_ALCOHOL_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Alcohol Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_ALCOHOL_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_ALCOHOL_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Alcohol Poisoning' AS "DATA_VARIABLE",
       100 * cast(N_ALCOHOL_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
       N_ALCOHOL_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- Benzo poisoning
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Benzo Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_BENZO_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_BENZO_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Benzo Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_BENZO_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_BENZO_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Benzo Poisoning' AS "DATA_VARIABLE",
       100 * cast(N_BENZO_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
       N_BENZO_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- Drug poisoning
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Drug Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_DRUG_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_DRUG_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Drug Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_DRUG_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_DRUG_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Drug Poisoning' AS "DATA_VARIABLE",
       100 * cast(N_DRUG_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
       N_DRUG_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- Other poisoning
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Other Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_OTHER_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_OTHER_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Other Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_OTHER_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_OTHER_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Other Poisoning' AS "DATA_VARIABLE",
       100 * cast(N_OTHER_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
       N_OTHER_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- Overdose
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Overdose' AS "DATA_VARIABLE",
      100 * cast(N_OVERDOSE_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_OVERDOSE_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Overdose' AS "DATA_VARIABLE",
      100 * cast(N_OVERDOSE_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_OVERDOSE_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Overdose' AS "DATA_VARIABLE",
       100 * cast(N_OVERDOSE_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
       N_OVERDOSE_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
-- Stimulant poisoning
  UNION ALL
    SELECT
      PERIOD,
      'All' as "COHORT",
      'Stimulant Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_STIMULANT_DIAGNOSED AS real) / N_OPIOID_PRESCRIBERS AS VALUE,
      N_STIMULANT_DIAGNOSED as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Chronic' as "COHORT",
      'Stimulant Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_STIMULANT_DIAGNOSED_CHRONIC AS real) / N_OPIOID_PRESCRIBERS_CHRONIC AS VALUE,
      N_STIMULANT_DIAGNOSED_CHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  UNION ALL
    SELECT
      PERIOD,
      'Non-chronic' as "COHORT",
      'Stimulant Poisoning' AS "DATA_VARIABLE",
      100 * cast(N_STIMULANT_DIAGNOSED_NONCHRONIC AS real) / N_OPIOID_PRESCRIBERS_NONCHRONIC AS VALUE,
      N_STIMULANT_DIAGNOSED_NONCHRONIC as TOOLTIP
    FROM ALL_AGGREGATES
  ) AS A
  WHERE cast(strftime('%Y', PERIOD) as integer) <= 2018 AND cast(strftime('%Y', PERIOD) as integer) >= 2009
  ORDER BY data_variable;