-- Load Source Database --

ATTACH DATABASE 'raw-data/original/box-health/R2767_Data.db' AS src;
-- ATTACH DATABASE ':memory:' AS src;
-- .restore 'src' 'raw-data/original/box-health/R2767_Data.db';


-- (O)pioid related events --

-- DROP TABLE IF EXISTS "ENCOUNTER_CATEGORY_COUNT";
-- CREATE TABLE "ENCOUNTER_CATEGORY_COUNT" AS
--     SELECT DISTINCT
--         CARE_SETTING_CATEGORY AS CARE_TYPE,
--         COUNT(ENCOUNTER_ID) AS ENCOUNTER_COUNT,
--         COUNT(CARE_SETTING_CATEGORY) AS CATEGORY_COUNT,
--         CATEGORY_COUNT / ENCOUNTER_COUNT AS CATEGORY_PERCENT
--     FROM src.ENCOUNTERS
--     GROUP BY CARE_SETTING_CATEGORY
--     ORDER BY CATEGORY_PERCENT;

-- DROP TABLE IF EXISTS "EMERGENCY_CATEGORY_PERCENT";
-- CREATE TABLE "ENCOUNTER_CATEGORY_PERCENTS"
--     SELECT
--         STUDY_ID,
--         COUNT(ENCOUNTER_ID) AS ENCOUNTER_COUNT,

--     WHERE
--         ENCOUNTER_ID IS 'E'

-- DROP TABLE IF EXISTS "ENCOUNTER_COUNT";
-- CREATE TABLE "ENCOUNTER_COUNT" AS
--     SELECT
--         COUNT(*)
--     FROM src.ENCOUNTERS;

DROP TABLE IF EXISTS "CATEGORY_COUNTS";
CREATE TABLE "CATEGORY_COUNTS" AS
    SELECT
        CARE_SETTING_CATEGORY AS CATEGORY,
        COUNT(DISTINCT STUDY_ID) AS UNIQUE_STUDY_IDS,
        COUNT(*) AS CATEGORY_TOTAL
    FROM src.ENCOUNTERS
    GROUP BY CARE_SETTING_CATEGORY
    ORDER BY UNIQUE_STUDY_IDS;

DROP TABLE IF EXISTS "INSURANCE_COUNTS_ALL";
CREATE TABLE "INSURANCE_COUNTS_ALL" AS
    SELECT
        strftime('%Y', ADMIT_TIME) || CASE 
            WHEN cast(strftime('%m', ADMIT_TIME) as integer) BETWEEN 1 AND 3 THEN '-01-01'
            WHEN cast(strftime('%m', ADMIT_TIME) as integer) BETWEEN 4 and 6 THEN '-04-01'
            WHEN cast(strftime('%m', ADMIT_TIME) as integer) BETWEEN 7 and 9 THEN '-07-01'
            ELSE '-10-01'
            END AS "PERIOD", -- Quarterly Period
        COUNT(*) AS TOTAL,
        SUM(COMMERCIAL_FLAG) AS COMMERCIAL,
        SUM(OTHERGOV_FLAG) AS OTHER_GOV,
        SUM(SELFPAY_FLAG) AS SELF_PAY,
        SUM(WORKERSCOMP_FLAG) AS WORKERS_COMP,
        SUM(INSTITUTIONALIZED_FLAG) AS INSTITUTIONALIZED,
        SUM(CHARITY_FLAG) AS CHARITY,
        SUM(MEDICARE_FLAG) AS MEDICARE,
        SUM(MEDICAID_FLAG) AS MEDICAID,
        SUM(NODATA_FLAG) AS NO_DATA
    FROM src.ENCOUNTERS
    GROUP BY PERIOD
    ORDER BY PERIOD;

DROP TABLE IF EXISTS "INSURANCE_COUNTS_CHRONIC";
CREATE TABLE "INSURANCE_COUNTS_CHRONIC" AS
    SELECT
        strftime('%Y', ADMIT_TIME) || CASE 
            WHEN cast(strftime('%m', ADMIT_TIME) as integer) BETWEEN 1 AND 3 THEN '-01-01'
            WHEN cast(strftime('%m', ADMIT_TIME) as integer) BETWEEN 4 and 6 THEN '-04-01'
            WHEN cast(strftime('%m', ADMIT_TIME) as integer) BETWEEN 7 and 9 THEN '-07-01'
            ELSE '-10-01'
            END AS "PERIOD", -- Quarterly Period
        COUNT(*) AS TOTAL,
        SUM(COMMERCIAL_FLAG) AS COMMERCIAL,
        SUM(OTHERGOV_FLAG) AS OTHER_GOV,
        SUM(SELFPAY_FLAG) AS SELF_PAY,
        SUM(WORKERSCOMP_FLAG) AS WORKERS_COMP,
        SUM(INSTITUTIONALIZED_FLAG) AS INSTITUTIONALIZED,
        SUM(CHARITY_FLAG) AS CHARITY,
        SUM(MEDICARE_FLAG) AS MEDICARE,
        SUM(MEDICAID_FLAG) AS MEDICAID,
        SUM(NODATA_FLAG) AS NO_DATA
    FROM src.ENCOUNTERS
    JOIN CHRONIC USING(STUDY_ID)
    WHERE IS_CHRONIC = 1
    GROUP BY PERIOD
    ORDER BY PERIOD;

DROP TABLE IF EXISTS "INSURANCE_COUNTS_OTHER";
CREATE TABLE "INSURANCE_COUNTS_OTHER" AS
    SELECT
        strftime('%Y', ADMIT_TIME) || CASE 
            WHEN cast(strftime('%m', ADMIT_TIME) as integer) BETWEEN 1 AND 3 THEN '-01-01'
            WHEN cast(strftime('%m', ADMIT_TIME) as integer) BETWEEN 4 and 6 THEN '-04-01'
            WHEN cast(strftime('%m', ADMIT_TIME) as integer) BETWEEN 7 and 9 THEN '-07-01'
            ELSE '-10-01'
            END AS "PERIOD", -- Quarterly Period
        COUNT(*) AS TOTAL,
        SUM(COMMERCIAL_FLAG) AS COMMERCIAL,
        SUM(OTHERGOV_FLAG) AS OTHER_GOV,
        SUM(SELFPAY_FLAG) AS SELF_PAY,
        SUM(WORKERSCOMP_FLAG) AS WORKERS_COMP,
        SUM(INSTITUTIONALIZED_FLAG) AS INSTITUTIONALIZED,
        SUM(CHARITY_FLAG) AS CHARITY,
        SUM(MEDICARE_FLAG) AS MEDICARE,
        SUM(MEDICAID_FLAG) AS MEDICAID,
        SUM(NODATA_FLAG) AS NO_DATA
    FROM src.ENCOUNTERS
    JOIN CHRONIC USING(STUDY_ID)
    WHERE IS_CHRONIC = 0
    GROUP BY PERIOD
    ORDER BY PERIOD;


DROP TABLE IF EXISTS "INSURANCE_COUNTS_AGG";
CREATE TABLE "INSURANCE_COUNTS_AGG" AS
    SELECT * FROM (
        SELECT
            PERIOD,
            TOTAL,
            COMMERCIAL,
            OTHER_GOV,
            SELF_PAY,
            WORKERS_COMP,
            INSTITUTIONALIZED,
            CHARITY,
            MEDICARE,
            MEDICAID,
            NO_DATA,
            "ALL" AS "COHORT"
        FROM INSURANCE_COUNTS_ALL
    UNION ALL
        SELECT
            PERIOD,
            TOTAL,
            COMMERCIAL,
            OTHER_GOV,
            SELF_PAY,
            WORKERS_COMP,
            INSTITUTIONALIZED,
            CHARITY,
            MEDICARE,
            MEDICAID,
            NO_DATA,
            "OPIOID_CHRONIC" AS "COHORT"
        FROM INSURANCE_COUNTS_CHRONIC
    UNION ALL
        SELECT
            PERIOD,
            TOTAL,
            COMMERCIAL,
            OTHER_GOV,
            SELF_PAY,
            WORKERS_COMP,
            INSTITUTIONALIZED,
            CHARITY,
            MEDICARE,
            MEDICAID,
            NO_DATA,
            "OPIOID_OTHER" AS "COHORT"
        FROM INSURANCE_COUNTS_OTHER
    ) AS AGG
    ORDER BY COHORT, PERIOD;